[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "divisor"
version = "0.1.2"
description = "fragment / denoise / process"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "opencv-python>=4.12.0.88",
    "nnll",
]
[project.scripts]
dvzr = "divisor.app:main"
divisor = "divisor.app:main"


[dependency-groups]
dev = [
    "pyright>=1.1.407",
    "ruff>=0.14.5",
]
fudoki = [
    "attrdict>=2.0.1",
    "matplotlib>=3.10.7",
    "timm>=1.0.22",
    "torchdiffeq>=0.2.5",
]
[tool.pyright]
include = ["divisor"]
exclude = [
  "**/__pycache__", # cache directories
  "./typings",      # generated type stubs
]
[tool.setuptools]
packages = ["divisor"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.md"]

[tool.uv]
package = true
preview = true

[tool.ruff]
line-length    = 160
include        = ["*.py"]
extend-exclude = ["**/__pycache__", "./typings"]

[tool.ruff.lint]
ignore = ["E731"]

[tool.pylint]
max-line-length = 140
ignore-paths    = ["^tests/.*$", "test_.*$"]
disable         = ["C0415"]

[tool.uv.sources]
nnll = { git = "https://github.com/darkshapes/nnll" }
