[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "divisor"
version = "0.1.4"
description = "fragment / denoise / process"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.1",
    "fire>=0.7.1",
    "nnll",
    "protobuf>=6.33.1",
    "sentencepiece>=0.2.1",
]
[project.scripts]
dvzr = "divisor.app:main"
divisor = "divisor.app:main"


[dependency-groups]
dev = [
    "pyright>=1.1.407",
    "pytest>=9.0.1",
    "ruff>=0.14.5",
]
[tool.pyright]
include = ["divisor"]
exclude = [
  "**/__pycache__", # cache directories
  "./typings",      # generated type stubs
]
[tool.setuptools]
packages = ["divisor"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.md"]

[tool.uv]
package = true
preview = true

[tool.uv.sources]
nnll = { git = "https://github.com/darkshapes/nnll" }
